const fs = require('fs/promises');
const path = require('path');
const { pathToFileURL } = require('url');

/**
 * Writes a `.md` twin for every doc page (`/x` -> `/x.md`), plus `llms.txt` and
 * `llms-full.txt`.
 *
 * Converts the built HTML, not the source MDX, with the same converter the
 * "Copy page" button uses: rendered HTML has Tabs, reusables, collapsibles, and
 * Mermaid already expanded. Build only, since `postBuild` never runs in dev.
 *
 * @param {import('@docusaurus/types').LoadContext} context
 * @param {{
 *   contentSelector?: string,
 *   exclude?: string[],
 *   includeSource?: boolean,
 *   llms?: false | { title?: string, description?: string, sections?: {prefix: string, label: string}[] },
 * }} options
 */
module.exports = function markdownPagesPlugin(context, options = {}) {
  const {
    contentSelector = '.theme-doc-markdown',
    exclude = ['/reusables/'],
    includeSource = true,
    llms = {},
  } = options;

  // Root-level pages head the sidebar, so they head the index too.
  const UNSECTIONED_LABEL = 'Getting Started';

  // The sidebar is folder-autogenerated, so there is no order to read. Mirrored
  // here by hand; unmatched routes fall under UNSECTIONED_LABEL.
  const DEFAULT_SECTIONS = [
    { prefix: '/text-to-signup', label: 'Text to Signup' },
    { prefix: '/1-click-verify', label: '1-Click Verify' },
    { prefix: '/1-click-signup', label: '1-Click Signup' },
    { prefix: '/1-click-health', label: '1-Click Health' },
    { prefix: '/reference', label: 'Reference' },
    { prefix: '/webhooks', label: 'Webhooks' },
  ];

  const converterPath = path.join(
    context.siteDir,
    'src/components/CopyPageButton/htmlToMarkdown.mjs'
  );

  const isExcluded = (route) => {
    return exclude.some((prefix) => {
      return route.startsWith(prefix);
    });
  };

  // `/guides/setup` -> `build/guides/setup.md`, `/` -> `build/index.md`.
  const toMarkdownPath = (outDir, route) => {
    const relative = route === '/' ? 'index' : route.replace(/^\/|\/$/g, '');

    return path.join(outDir, `${relative}.md`);
  };

  // `/` is written as `index.md`, so its URL must match.
  const toMarkdownUrl = (siteConfig, route) => {
    const target = route === '/' ? '/index' : route.replace(/\/$/, '');

    return `${toAbsoluteUrl(siteConfig, target)}.md`;
  };

  const toAbsoluteUrl = (siteConfig, route) => {
    return new URL(
      path.posix.join(siteConfig.baseUrl || '/', route),
      siteConfig.url
    ).href;
  };

  // Fallback description: first line that is prose, not a heading/quote/table/fence.
  const firstParagraph = (markdown) => {
    const paragraph = markdown.split('\n').find((line) => {
      return line.trim() && !/^([#>|`\-!*]|\d+\.)/.test(line.trim());
    });

    if (!paragraph) {
      return '';
    }

    const text = paragraph.replace(/[*_`]/g, '').trim();

    return text.length > 180 ? `${text.slice(0, 177)}...` : text;
  };

  // A heading with neither content nor a subsection under it means the
  // conversion dropped something, which is otherwise silent. A deeper heading
  // next is normal nesting, so only a sibling or shallower one counts.
  const emptyHeadings = (markdown) => {
    const lines = markdown.split('\n');

    const level = (line) => {
      const match = /^(#{1,6})\s/.exec(line);

      return match ? match[1].length : 0;
    };

    return lines
      .map((line, index) => {
        const depth = level(line);

        if (!depth) {
          return null;
        }

        const next = lines.slice(index + 1).find((candidate) => {
          return candidate.trim() && candidate.trim() !== '---';
        });

        if (!next) {
          return line.trim();
        }

        const nextDepth = level(next);

        return nextDepth && nextDepth <= depth ? line.trim() : null;
      })
      .filter(Boolean);
  };

  const sectionFor = (sections, route) => {
    const match = sections.find((section) => {
      return route.startsWith(section.prefix);
    });

    return match ? match.label : UNSECTIONED_LABEL;
  };

  // Landing page and each section's `overview` first, then alphabetical.
  const byReadingOrder = (a, b) => {
    const weigh = (page) => {
      if (page.route === '/') {
        return 0;
      }

      return /\/overview$/.test(page.route) ? 0 : 1;
    };

    return weigh(a) - weigh(b) || a.route.localeCompare(b.route);
  };

  const buildLlmsTxt = (pages, siteConfig, sections) => {
    const lines = [
      `# ${llms.title || siteConfig.title}`,
      '',
      `> ${llms.description || siteConfig.tagline}`,
      '',
      'Every page below is also available as Markdown at the linked `.md` URL.',
      'The whole documentation set in one file: ' +
        `${toAbsoluteUrl(siteConfig, '/llms-full.txt')}`,
    ];

    const labels = [
      UNSECTIONED_LABEL,
      ...sections.map((section) => {
        return section.label;
      }),
    ];

    labels.forEach((label) => {
      const inSection = pages
        .filter((page) => {
          return page.section === label;
        })
        .sort(byReadingOrder);

      if (inSection.length === 0) {
        return;
      }

      lines.push('', `## ${label}`, '');

      inSection.forEach((page) => {
        const suffix = page.description ? `: ${page.description}` : '';

        lines.push(`- [${page.title}](${page.markdownUrl})${suffix}`);
      });
    });

    return `${lines.join('\n')}\n`;
  };

  // The docs import the graphic-variant reusables several times per page, so the
  // same download lists repeat verbatim. Harmless on a rendered page, expensive
  // in a prompt: they were ~19% of the file and, chunked for RAG, produce chunks
  // with no unique content. First run is kept in full, later identical runs
  // become a pointer to it. llms-full.txt only; the .md twins stay faithful.
  const ASSET_PATTERN = /\/img\/graphics\//;

  const LABEL_PATTERN = /^\*\*[^\n]+\*\*:?$/;

  const collapseRepeatedAssets = (markdown, seenRuns, page) => {
    const blocks = markdown.split(/\n{2,}/);

    const output = [];

    let run = [];

    const flush = () => {
      if (run.length === 0) {
        return;
      }

      const text = run.join('\n\n');

      // A run of labels and separators with no assets is ordinary content.
      if (!ASSET_PATTERN.test(text)) {
        output.push(text);
        run = [];

        return;
      }

      const first = seenRuns.get(text);

      if (first) {
        output.push(`_(Same asset list as ${first.title}: ${first.url})_`);
      } else {
        seenRuns.set(text, { title: page.title, url: page.markdownUrl });
        output.push(text);
      }

      run = [];
    };

    blocks.forEach((rawBlock) => {
      const block = rawBlock.trim();

      if (!block) {
        return;
      }

      const isRunnable =
        ASSET_PATTERN.test(block) ||
        LABEL_PATTERN.test(block) ||
        block === '---';

      if (isRunnable) {
        run.push(block);

        return;
      }

      flush();
      output.push(block);
    });

    flush();

    return output.join('\n\n');
  };

  const buildLlmsFullTxt = (pages, siteConfig, sections) => {
    const ordered = [...pages].sort((a, b) => {
      const rank = (page) => {
        const index = sections.findIndex((section) => {
          return section.label === page.section;
        });

        // Unsectioned lead, as in llms.txt.
        return index === -1 ? -1 : index;
      };

      return rank(a) - rank(b) || byReadingOrder(a, b);
    });

    const header = [
      `# ${llms.title || siteConfig.title}`,
      '',
      `> ${llms.description || siteConfig.tagline}`,
      '',
      `Full documentation, ${ordered.length} pages, one per section below.`,
      'Index: ' + toAbsoluteUrl(siteConfig, '/llms.txt'),
    ].join('\n');

    // Pages already carry their `# Title` and `Source:` line. Two edits apply
    // here and not to the `.md` twins, which stay a faithful mirror of the page:
    // titles get their section (a bare `# Setup` repeats across products), and
    // alt-less images are dropped unless they are a link's only content.
    const seenRuns = new Map();

    const body = ordered
      .map((page) => {
        const heading =
          page.section === UNSECTIONED_LABEL ||
          page.title.startsWith(page.section)
            ? `# ${page.title}`
            : `# ${page.section}: ${page.title}`;

        // A function replacement, so `$` in a title is not read as a reference.
        const qualified = page.markdown.replace(/^#\s+.*$/m, () => {
          return `${heading}\nSource: ${page.markdownUrl}`;
        });

        return (
          collapseRepeatedAssets(qualified, seenRuns, page)
            // Standalone only: an image wrapped in a link is that link's only
            // text, and removing it leaves `[](url)`, which says even less than
            // an alt-less image did.
            .replace(/(?<!\[)!\[\]\([^)]*\)[ \t]*\n?/g, '')
            // Safety net for any other source of textless links. The `!`
            // lookbehind keeps it off the `[](...)` inside an image.
            .replace(/(?<!!)\[\]\(([^)]*)\)/g, '<$1>')
            .replace(/\n{3,}/g, '\n\n')
            .trim()
        );
      })
      .join('\n\n---\n\n');

    return `${header}\n\n---\n\n${body}\n`;
  };

  return {
    name: 'markdown-pages',

    async postBuild({ outDir, routesPaths, siteConfig }) {
      // Dynamic import: the converter is ESM because the browser bundle needs it that way.
      const { htmlToMarkdown } = await import(
        pathToFileURL(converterPath).href
      );

      const { JSDOM } = require('jsdom');

      const sections = llms && llms.sections ? llms.sections : DEFAULT_SECTIONS;

      const pages = [];

      let skipped = 0;

      for (const route of routesPaths) {
        if (isExcluded(route)) {
          skipped += 1;
          continue;
        }

        const htmlPath = path.join(outDir, route, 'index.html');

        let html;

        try {
          html = await fs.readFile(htmlPath, 'utf8');
        } catch {
          // Redirects and other routes with no HTML of their own.
          skipped += 1;
          continue;
        }

        const pageUrl = toAbsoluteUrl(siteConfig, route);

        // With a URL, `element.href` resolves and links come out absolute.
        const { window } = new JSDOM(html, { url: pageUrl });

        const { document } = window;

        const contentElement = document.querySelector(contentSelector);

        if (!contentElement) {
          window.close();
          skipped += 1;
          continue;
        }

        let markdown = htmlToMarkdown(contentElement);

        const headingElement = contentElement.querySelector('h1');

        const metaElement = document.querySelector('meta[name="description"]');

        const title = (
          (headingElement && headingElement.textContent) ||
          document.title ||
          route
        ).trim();

        const description = metaElement
          ? metaElement.getAttribute('content').trim()
          : '';

        window.close();

        if (!markdown) {
          skipped += 1;
          continue;
        }

        if (includeSource) {
          markdown = `${markdown}\n\n---\n\nSource: ${pageUrl}\n`;
        }

        const markdownPath = toMarkdownPath(outDir, route);

        await fs.mkdir(path.dirname(markdownPath), { recursive: true });
        await fs.writeFile(markdownPath, markdown, 'utf8');

        pages.push({
          route,
          title,
          description: description || firstParagraph(markdown),
          markdown,
          markdownUrl: toMarkdownUrl(siteConfig, route),
          section: sectionFor(sections, route),
          emptyHeadings: emptyHeadings(markdown),
        });
      }

      console.log(
        `[markdown-pages] wrote ${pages.length} .md files (${skipped} routes skipped)`
      );

      pages.forEach((page) => {
        page.emptyHeadings.forEach((heading) => {
          console.warn(
            `[markdown-pages] empty section: ${page.route} -> ${heading}`
          );
        });
      });

      if (llms === false || pages.length === 0) {
        return;
      }

      await fs.writeFile(
        path.join(outDir, 'llms.txt'),
        buildLlmsTxt(pages, siteConfig, sections),
        'utf8'
      );

      await fs.writeFile(
        path.join(outDir, 'llms-full.txt'),
        buildLlmsFullTxt(pages, siteConfig, sections),
        'utf8'
      );

      console.log('[markdown-pages] wrote llms.txt and llms-full.txt');
    },
  };
};
