const fs = require('fs/promises');
const path = require('path');
const { pathToFileURL } = require('url');

/**
 * Writes a `.md` twin for every doc page (`/x` -> `/x.md`), plus `llms.txt` and
 * `llms-full.txt`.
 *
 * Converts the built HTML, not the source MDX, with the same converter the
 * "Copy page" button uses: rendered HTML has Tabs, reusables, collapsibles, and
 * Mermaid already expanded. Build only, since `postBuild` never runs in dev.
 *
 * @param {import('@docusaurus/types').LoadContext} context
 * @param {{
 *   contentSelector?: string,
 *   categorySelector?: string,
 *   exclude?: string[],
 *   includeSource?: boolean,
 *   llms?: false | { title?: string, description?: string, sections?: {prefix: string, label: string}[] },
 * }} options
 */
const ZERO_WIDTH = /[\u200b\u200c\u200d\ufeff]/g;

const humanSize = (text) => {
  const bytes = Buffer.byteLength(text, 'utf8');

  return bytes < 1024 ? `${bytes} B` : `${Math.round(bytes / 1024)} KB`;
};

module.exports = function markdownPagesPlugin(context, options = {}) {
  const {
    contentSelector = '.theme-doc-markdown',
    // Auto-generated category landing pages (a card list of sub-pages, e.g.
    // `/1-click-health`) have no `.theme-doc-markdown` of their own.
    categorySelector = '[class*="generatedIndexPage"]',
    exclude = ['/reusables/'],
    includeSource = true,
    llms = {},
  } = options;

  // Root-level pages head the sidebar, so they head the index too.
  const UNSECTIONED_LABEL = 'Getting Started';

  // The sidebar is folder-autogenerated, so there is no order to read. Mirrored
  // here by hand; unmatched routes fall under UNSECTIONED_LABEL.
  const DEFAULT_SECTIONS = [
    { prefix: '/text-to-signup', label: 'Text to Signup' },
    { prefix: '/1-click-verify', label: '1-Click Verify' },
    { prefix: '/1-click-signup', label: '1-Click Signup' },
    { prefix: '/1-click-health', label: '1-Click Health' },
    { prefix: '/reference', label: 'Reference' },
    { prefix: '/webhooks', label: 'Webhooks' },
  ];

  const converterPath = path.join(
    context.siteDir,
    'src/components/CopyPageButton/htmlToMarkdown.mjs'
  );

  const isExcluded = (route) => {
    return exclude.some((prefix) => {
      return route.startsWith(prefix);
    });
  };

  // `/guides/setup` -> `build/guides/setup.md`, `/` -> `build/index.md`.
  const toMarkdownPath = (outDir, route) => {
    const relative = route === '/' ? 'index' : route.replace(/^\/|\/$/g, '');

    return path.join(outDir, `${relative}.md`);
  };

  // `/` is written as `index.md`, so its URL must match.
  const toMarkdownUrl = (siteConfig, route) => {
    const target = route === '/' ? '/index' : route.replace(/\/$/, '');

    return `${toAbsoluteUrl(siteConfig, target)}.md`;
  };

  const toAbsoluteUrl = (siteConfig, route) => {
    return new URL(
      path.posix.join(siteConfig.baseUrl || '/', route),
      siteConfig.url
    ).href;
  };

  // Fallback description: first line that is prose, not a heading/quote/table/fence.
  const firstParagraph = (markdown) => {
    const paragraph = markdown.split('\n').find((line) => {
      return line.trim() && !/^([#>|`\-!*]|\d+\.)/.test(line.trim());
    });

    if (!paragraph) {
      return '';
    }

    const text = paragraph.replace(/[*_`]/g, '').trim();

    return text.length > 180 ? `${text.slice(0, 177)}...` : text;
  };

  // A heading with neither content nor a subsection under it means the
  // conversion dropped something, which is otherwise silent. A deeper heading
  // next is normal nesting, so only a sibling or shallower one counts.
  const emptyHeadings = (markdown) => {
    const lines = markdown.split('\n');

    const level = (line) => {
      const match = /^(#{1,6})\s/.exec(line);

      return match ? match[1].length : 0;
    };

    return lines
      .map((line, index) => {
        const depth = level(line);

        if (!depth) {
          return null;
        }

        const next = lines.slice(index + 1).find((candidate) => {
          return candidate.trim() && candidate.trim() !== '---';
        });

        if (!next) {
          return line.trim();
        }

        const nextDepth = level(next);

        return nextDepth && nextDepth <= depth ? line.trim() : null;
      })
      .filter(Boolean);
  };

  // So an agent following a link from one `.md` file lands on another `.md`
  // file instead of the HTML page. Only same-site doc routes qualify: other
  // origins (the demo app, Calendly) and paths that already carry their own
  // extension (assets, files) link through unchanged, as does anything under
  // an excluded prefix, since those never get a `.md` twin written.
  const toHrefRewriter = (siteConfig, absoluteUrl) => {
    const siteOrigin = new URL(siteConfig.url).origin;

    return (element, attribute) => {
      const href = absoluteUrl(element, attribute);

      let target;

      try {
        target = new URL(href);
      } catch {
        return href;
      }

      const isDocRoute =
        target.origin === siteOrigin &&
        !path.extname(target.pathname) &&
        !isExcluded(target.pathname);

      if (!isDocRoute) {
        return href;
      }

      return `${toMarkdownUrl(siteConfig, target.pathname)}${target.search}${
        target.hash
      }`;
    };
  };

  const toInternalLinkHandler = (rewriteHref) => {
    return (element, context) => {
      const text = context.inline(element).trim();

      if (!text) {
        return '';
      }

      const rawHref = element.getAttribute('href') || '';

      if (!rawHref || rawHref.startsWith('#')) {
        return text;
      }

      return `[${text}](${rewriteHref(element, 'href')})`;
    };
  };

  // Category landing pages (and any hand-authored `<DocCardList>`) render each
  // link as a card: an `<a>` wrapping its own heading and description, which
  // the generic `a` handler would inline as garbled nested markdown. Read the
  // two pieces directly and emit one list item instead.
  const toCardMatcher = (rewriteHref) => {
    return {
      test: (element) => {
        return (
          element.tagName === 'A' &&
          /(^|\s)theme-doc-card-container(\s|$)/.test(element.className || '')
        );
      },

      handle: (element) => {
        const href = element.getAttribute('href') || '';

        const titleElement = element.querySelector('.theme-doc-card-title');

        const title = (titleElement || element).textContent.trim();

        if (!href || !title) {
          return '';
        }

        const descriptionElement = element.querySelector(
          '.theme-doc-card-description'
        );

        const description = descriptionElement
          ? descriptionElement.textContent.trim()
          : '';

        const suffix = description ? `: ${description}` : '';

        return `- [${title}](${rewriteHref(element, 'href')})${suffix}\n`;
      },
    };
  };

  // A search index of our own, so nothing downstream has to translate HTML
  // routes into `.md` ones. `search-doc.json` from docusaurus-lunr-search has
  // the same shape but its URLs point at the HTML pages, and its format is that
  // plugin's business rather than ours.
  //
  // One entry per heading plus one per page, each carrying the section text, so
  // a keyword match lands on `page.md#section` instead of just the page.
  const SECTION_HEADINGS = 'h2, h3, h4';

  const headingText = (heading) => {
    return (heading.textContent || '').replace(ZERO_WIDTH, '').trim();
  };

  const collectSections = (contentElement, page) => {
    const sections = [];

    contentElement.querySelectorAll(SECTION_HEADINGS).forEach((heading) => {
      const anchor = heading.getAttribute('id');

      if (!anchor) {
        return;
      }

      // Everything up to the next heading belongs to this section.
      const body = [];

      let sibling = heading.nextElementSibling;

      while (sibling && !sibling.matches(SECTION_HEADINGS)) {
        body.push(sibling.textContent || '');
        sibling = sibling.nextElementSibling;
      }

      sections.push({
        type: 'section',
        title: headingText(heading),
        page: page.title,
        section: page.section,
        url: `${page.markdownUrl}#${anchor}`,
        content: body.join(' ').replace(/\s+/g, ' ').trim(),
      });
    });

    return sections;
  };

  // Docusaurus renders the sidebar neighbours as a pagination nav, outside the
  // content element, so the converter never sees them. Read them here and carry
  // them into the footer: an agent can then walk a product in order instead of
  // guessing what follows.
  const readPagination = (document, rewriteHref) => {
    const read = (modifier) => {
      const link = document.querySelector(`.pagination-nav__link--${modifier}`);

      if (!link) {
        return null;
      }

      const label = link.querySelector('.pagination-nav__label') || link;

      return {
        title: (label.textContent || '').replace(ZERO_WIDTH, '').trim(),
        url: rewriteHref(link, 'href'),
      };
    };

    return { previous: read('prev'), next: read('next') };
  };

  const sectionFor = (sections, route) => {
    const match = sections.find((section) => {
      return route.startsWith(section.prefix);
    });

    return match ? match.label : UNSECTIONED_LABEL;
  };

  // Landing page and each section's `overview` first, then alphabetical.
  const byReadingOrder = (a, b) => {
    const weigh = (page) => {
      if (page.route === '/') {
        return 0;
      }

      return /\/overview$/.test(page.route) ? 0 : 1;
    };

    return weigh(a) - weigh(b) || a.route.localeCompare(b.route);
  };

  const buildLlmsTxt = (pages, siteConfig, sections, sizes) => {
    const lines = [
      `# ${llms.title || siteConfig.title}`,
      '',
      `> ${llms.description || siteConfig.tagline}`,
      '',
      'Every page below is also available as Markdown at the linked `.md` URL.',
      `Searchable index of every page and section (${
        sizes.index
      }, meant to be filtered rather than read whole): ${toAbsoluteUrl(
        siteConfig,
        '/search-index.json'
      )}`,
      `The whole documentation set in one file (${sizes.full}): ` +
        `${toAbsoluteUrl(siteConfig, '/llms-full.txt')}`,
    ];

    const labels = [
      UNSECTIONED_LABEL,
      ...sections.map((section) => {
        return section.label;
      }),
    ];

    labels.forEach((label) => {
      const inSection = pages
        .filter((page) => {
          return page.section === label;
        })
        .sort(byReadingOrder);

      if (inSection.length === 0) {
        return;
      }

      lines.push('', `## ${label}`, '');

      const bundle = sizes.bundles && sizes.bundles.get(label);

      if (bundle) {
        lines.push(
          `All of ${label} in one file (${bundle.size}): ${toAbsoluteUrl(
            siteConfig,
            bundle.path
          )}`,
          ''
        );
      }

      inSection.forEach((page) => {
        const suffix = page.description ? `: ${page.description}` : '';

        // Size lets a client decide whether to fetch a page whole, and check
        // afterwards that it got all of it.
        lines.push(
          `- [${page.title}](${page.markdownUrl}) (${humanSize(
            page.markdown
          )})${suffix}`
        );
      });
    });

    return `${lines.join('\n')}\n`;
  };

  // The docs import the graphic-variant reusables several times per page, so the
  // same download lists repeat verbatim. Harmless on a rendered page, expensive
  // in a prompt: they were ~19% of the file and, chunked for RAG, produce chunks
  // with no unique content. First run is kept in full, later identical runs
  // become a pointer to it. llms-full.txt only; the .md twins stay faithful.
  const ASSET_PATTERN = /\/img\/graphics\//;

  const LABEL_PATTERN = /^\*\*[^\n]+\*\*:?$/;

  const collapseRepeatedAssets = (markdown, seenRuns, page) => {
    const blocks = markdown.split(/\n{2,}/);

    const output = [];

    let run = [];

    const flush = () => {
      if (run.length === 0) {
        return;
      }

      const text = run.join('\n\n');

      // A run of labels and separators with no assets is ordinary content.
      if (!ASSET_PATTERN.test(text)) {
        output.push(text);
        run = [];

        return;
      }

      const first = seenRuns.get(text);

      if (first) {
        output.push(`_(Same asset list as ${first.title}: ${first.url})_`);
      } else {
        seenRuns.set(text, { title: page.title, url: page.markdownUrl });
        output.push(text);
      }

      run = [];
    };

    blocks.forEach((rawBlock) => {
      const block = rawBlock.trim();

      if (!block) {
        return;
      }

      const isRunnable =
        ASSET_PATTERN.test(block) ||
        LABEL_PATTERN.test(block) ||
        block === '---';

      if (isRunnable) {
        run.push(block);

        return;
      }

      flush();
      output.push(block);
    });

    flush();

    return output.join('\n\n');
  };

  const buildLlmsFullTxt = (pages, siteConfig, sections, product) => {
    const ordered = [...pages].sort((a, b) => {
      const rank = (page) => {
        const index = sections.findIndex((section) => {
          return section.label === page.section;
        });

        // Unsectioned lead, as in llms.txt.
        return index === -1 ? -1 : index;
      };

      return rank(a) - rank(b) || byReadingOrder(a, b);
    });

    const title = product
      ? `${llms.title || siteConfig.title}: ${product}`
      : llms.title || siteConfig.title;

    const scope = product
      ? `Every ${product} page, ${ordered.length} in total.`
      : `Full documentation, ${ordered.length} pages, one per section below.`;

    const header = [
      `# ${title}`,
      '',
      `> ${llms.description || siteConfig.tagline}`,
      '',
      scope,
      'Index: ' + toAbsoluteUrl(siteConfig, '/llms.txt'),
    ].join('\n');

    // Pages already carry their `# Title` and `Source:` line. Two edits apply
    // here and not to the `.md` twins, which stay a faithful mirror of the page:
    // titles get their section (a bare `# Setup` repeats across products), and
    // alt-less images are dropped unless they are a link's only content.
    const seenRuns = new Map();

    const body = ordered
      .map((page) => {
        const heading =
          page.section === UNSECTIONED_LABEL ||
          page.title.startsWith(page.section)
            ? `# ${page.title}`
            : `# ${page.section}: ${page.title}`;

        // A function replacement, so `$` in a title is not read as a reference.
        const qualified = page.markdown.replace(/^#\s+.*$/m, () => {
          return `${heading}\nSource: ${page.markdownUrl}`;
        });

        return (
          collapseRepeatedAssets(qualified, seenRuns, page)
            // Standalone only: an image wrapped in a link is that link's only
            // text, and removing it leaves `[](url)`, which says even less than
            // an alt-less image did.
            .replace(/(?<!\[)!\[\]\([^)]*\)[ \t]*\n?/g, '')
            // Safety net for any other source of textless links. The `!`
            // lookbehind keeps it off the `[](...)` inside an image.
            .replace(/(?<!!)\[\]\(([^)]*)\)/g, '<$1>')
            .replace(/\n{3,}/g, '\n\n')
            .trim()
        );
      })
      .join('\n\n---\n\n');

    return `${header}\n\n---\n\n${body}\n`;
  };

  return {
    name: 'markdown-pages',

    async postBuild({ outDir, routesPaths, siteConfig }) {
      // Dynamic import: the converter is ESM because the browser bundle needs it that way.
      const { htmlToMarkdown, absoluteUrl } = await import(
        pathToFileURL(converterPath).href
      );

      const { JSDOM } = require('jsdom');

      const rewriteHref = toHrefRewriter(siteConfig, absoluteUrl);

      const converterOverrides = {
        handlers: { a: toInternalLinkHandler(rewriteHref) },
        matchers: [toCardMatcher(rewriteHref)],
      };

      const sections = llms && llms.sections ? llms.sections : DEFAULT_SECTIONS;

      const pages = [];

      let skipped = 0;

      for (const route of routesPaths) {
        if (isExcluded(route)) {
          skipped += 1;
          continue;
        }

        const htmlPath = path.join(outDir, route, 'index.html');

        let html;

        try {
          html = await fs.readFile(htmlPath, 'utf8');
        } catch {
          // Redirects and other routes with no HTML of their own.
          skipped += 1;
          continue;
        }

        const pageUrl = toAbsoluteUrl(siteConfig, route);

        // With a URL, `element.href` resolves and links come out absolute.
        const { window } = new JSDOM(html, { url: pageUrl });

        const { document } = window;

        const contentElement =
          document.querySelector(contentSelector) ||
          document.querySelector(categorySelector);

        if (!contentElement) {
          window.close();
          skipped += 1;
          continue;
        }

        let markdown = htmlToMarkdown(contentElement, converterOverrides);

        const headingElement = contentElement.querySelector('h1');

        const metaElement = document.querySelector('meta[name="description"]');

        const title = (
          (headingElement && headingElement.textContent) ||
          document.title ||
          route
        ).trim();

        const metaDescription = metaElement
          ? metaElement.getAttribute('content').trim()
          : '';

        const pagination = readPagination(document, rewriteHref);

        const pageSections = collectSections(contentElement, {
          title,
          section: sectionFor(sections, route),
          markdownUrl: toMarkdownUrl(siteConfig, route),
        });

        window.close();

        if (!markdown) {
          skipped += 1;
          continue;
        }

        // Read before the footer is appended, or a list-only page (a category
        // landing page, say) with no meta description would pick up its own
        // footer as its "first paragraph".
        const description = metaDescription || firstParagraph(markdown);

        pages.push({
          route,
          title,
          description,
          markdown,
          pageUrl,
          markdownUrl: toMarkdownUrl(siteConfig, route),
          section: sectionFor(sections, route),
          sections: pageSections,
          pagination,
          emptyHeadings: emptyHeadings(markdown),
        });
      }

      // The footer is built once every page is known, because the section link
      // points at a category landing page that may not have been converted yet.
      const generatedRoutes = new Set(
        pages.map((page) => {
          return page.route;
        })
      );

      const twinUrls = new Set(
        pages.map((page) => {
          return page.markdownUrl;
        })
      );

      // A sidebar neighbour can be a page we do not publish, a reusable fragment
      // for instance. Those links resolve to nothing in Markdown, so leave them out.
      const navLinkFor = (neighbour, skipUrl) => {
        if (
          !neighbour ||
          !twinUrls.has(neighbour.url) ||
          neighbour.url === skipUrl
        ) {
          return null;
        }

        return neighbour;
      };

      const sectionLinkFor = (route) => {
        const rule = sections.find((section) => {
          return route.startsWith(section.prefix);
        });

        // Skip the category page itself, and any section whose landing page has
        // no twin of its own.
        if (
          !rule ||
          route === rule.prefix ||
          !generatedRoutes.has(rule.prefix)
        ) {
          return null;
        }

        return {
          label: rule.label,
          url: toMarkdownUrl(siteConfig, rule.prefix),
        };
      };

      for (const page of pages) {
        const lines = [];

        if (includeSource) {
          lines.push(`Source: ${page.pageUrl}`);
        }

        const sectionLink = sectionLinkFor(page.route);

        if (sectionLink) {
          lines.push(`Section: ${sectionLink.label} — ${sectionLink.url}`);
        }

        // The category page is the first entry in its own section, so on the
        // section's first child it is both Section and Previous. Say it once.
        const previous = navLinkFor(
          page.pagination.previous,
          sectionLink && sectionLink.url
        );

        if (previous) {
          lines.push(`Previous: ${previous.title} — ${previous.url}`);
        }

        const next = navLinkFor(page.pagination.next);

        if (next) {
          lines.push(`Next: ${next.title} — ${next.url}`);
        }

        if (lines.length > 0) {
          page.markdown = `${page.markdown}\n\n---\n\n${lines.join('\n')}\n`;
        }

        const markdownPath = toMarkdownPath(outDir, page.route);

        await fs.mkdir(path.dirname(markdownPath), { recursive: true });
        await fs.writeFile(markdownPath, page.markdown, 'utf8');
      }

      console.log(
        `[markdown-pages] wrote ${pages.length} .md files (${skipped} routes skipped)`
      );

      pages.forEach((page) => {
        page.emptyHeadings.forEach((heading) => {
          console.warn(
            `[markdown-pages] empty section: ${page.route} -> ${heading}`
          );
        });
      });

      if (pages.length === 0) {
        return;
      }

      if (llms !== false) {
        const bundles = [];

        const llmsFullTxt = buildLlmsFullTxt(pages, siteConfig, sections);

        await fs.writeFile(
          path.join(outDir, 'llms-full.txt'),
          llmsFullTxt,
          'utf8'
        );

        // Sorted so the file is stable even if route order ever shifts.
        const searchIndex = pages
          .flatMap((page) => {
            return [
              {
                type: 'page',
                title: page.title,
                section: page.section,
                url: page.markdownUrl,
                content: page.description,
              },
              ...page.sections,
            ];
          })
          .sort((a, b) => {
            return a.url.localeCompare(b.url);
          });

        const searchIndexJson = `${JSON.stringify({ entries: searchIndex })}\n`;

        await fs.writeFile(
          path.join(outDir, 'search-index.json'),
          searchIndexJson,
          'utf8'
        );

        // A per product bundle, so "walk me through this integration" is one
        // fetch instead of four, with no page missed.
        for (const rule of sections) {
          const productPages = pages.filter((page) => {
            return page.section === rule.label;
          });

          if (productPages.length === 0) {
            continue;
          }

          const bundle = buildLlmsFullTxt(
            productPages,
            siteConfig,
            sections,
            rule.label
          );

          const bundlePath = path.join(outDir, rule.prefix, 'llms-full.txt');

          await fs.mkdir(path.dirname(bundlePath), { recursive: true });
          await fs.writeFile(bundlePath, bundle, 'utf8');

          bundles.push([rule.label, `${rule.prefix}/llms-full.txt`, bundle]);
        }

        const llmsTxt = buildLlmsTxt(pages, siteConfig, sections, {
          full: humanSize(llmsFullTxt),
          index: humanSize(searchIndexJson),
          bundles: new Map(
            bundles.map(([label, bundlePath, bundle]) => {
              return [label, { path: bundlePath, size: humanSize(bundle) }];
            })
          ),
        });

        await fs.writeFile(path.join(outDir, 'llms.txt'), llmsTxt, 'utf8');

        console.log(
          `[markdown-pages] wrote llms.txt, llms-full.txt, and search-index.json (${searchIndex.length} entries)`
        );
      }
    },
  };
};
